global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
    - job_name: 'currency-service-1'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: ['currency-rate-service-1:8085']

    - job_name: 'currency-service-2'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: ['currency-rate-service-2:8085']

    - job_name: 'processing-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
       - targets: ['exchange-processing-service:8090']

    - job_name: 'auth-service'
      metrics_path: '/actuator/prometheus'
      static_configs:
       - targets: ['auth-service:9000']