server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:auth-db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2

  zipkin:
    enabled: false
    baseUrl: http://${cloud.zipkin-host}:9411
  sleuth:
    sampler:
      percentage: 1

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka

management:
  endpoints:
    enabled-by-default: true

    web:
      exposure:
        include: "*"
